[theme]
base                     = "light"
primaryColor             = "#1C5440"
backgroundColor          = "#FBEFE4"
secondaryBackgroundColor = "#F3E3D5"
textColor                = "#2A211B"
font                     = "serif"

[server]
headless = true
